title:             Contemporary Poetics of Nicaragua
email:             jordanhallbauer@ucsb.edu
description:       Updates on Nicaraguan social movements and collection of protest literature
author:            Jordan Hallbauer
baseurl:          "/jordanhallbauer.github.io"
url:              "127.0.0.1:4000/jordanhallbauer.github.io/"


collections:
  pages:
    output: true
    permalink: /:name

# Social Profiles
twitter_username:  HallbauerJordan
github_username:   jordanhallbauer
facebook_username: Jordan Hallbauer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
