title:             Jordan Hallbauer
email:             jordanhallbauer@ucsb.edu
description:       This is a site for storing and sharing my information and projects past and present, welcome!
author:            Jordan Hallbauer
baseurl:          "/jordanhallbauer.github.io"
url:              "localhost:4000"


collections:
  pages:
    output: true
    permalink: /:name

# Social Profiles
twitter_username:  HallbauerJordan
github_username:   jordanhallbauer
facebook_username: Jordan Hallbauer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
